### ISSUE TITLE
Compile fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by lixiangnlp** [facebook/wangle#13]
/usr/bin/ld: warning: libboost_thread.so.1.59.0, needed by /usr/local/lib/../lib/libfolly.so, may conflict with libboost_thread.so.1.54.0
/usr/bin/ld: warning: libboost_system.so.1.59.0, needed by /usr/local/lib/../lib/libfolly.so, may conflict with libboost_system.so.1.54.0
/usr/bin/ld: ../gmock/src/gmock-build/libgmock.a(gtest-all.cc.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [bin/AcceptorTest] error 1
make[1]: *** [CMakeFiles/AcceptorTest.dir/all] error 2
make: *** [all] error 2

I can not find the solution for the error.

uname -a:

Linux lixiang-ubuntu 3.16.0-50-generic #67~14.04.1-Ubuntu SMP Fri Oct 2 22:07:51 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by js7222** [comment]
I have the same issue on ubuntu 15.04

**Comment by js7222** [comment]
I have the same issue on ubuntu 15.04

**Comment by renanbs** [comment]
Any ideas? I have the same issue with Arch Linux

**Comment by lixiangnlp** [comment]
put the option -lpthread at the end of the cxxflags

**Comment by renanbs** [comment]
Now I have another error:
```cmake
[  1%] Building CXX object CMakeFiles/wangle.dir/acceptor/Acceptor.cpp.o
In file included from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/acceptor/Acceptor.h:14:0,
                 from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/acceptor/Acceptor.cpp:10:
/home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/acceptor/ConnectionManager.h: In instantiation of 'static wangle::ConnectionManager::UniquePtr wangle::ConnectionManager::makeUnique(Args&& ...) [with Args = {folly::EventBase*&, const std::chrono::duration<long int, std::ratio<1l, 1000l> >&, wangle::Acceptor*}; wangle::ConnectionManager::UniquePtr = std::unique_ptr<wangle::ConnectionManager, folly::DelayedDestruction::Destructor>]':
/home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/acceptor/Acceptor.cpp:87:54:   required from here
/home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/acceptor/ConnectionManager.h:63:58: error: no matching function for call to 'make_unique(folly::EventBase*&, const std::chrono::duration<long int, std::ratio<1l, 1000l> >&, wangle::Acceptor*)'
  return folly::make_unique<ConnectionManager, Destructor>(
                                                          ^
In file included from /usr/include/folly/io/Cursor.h:31:0,
                 from /usr/include/folly/io/async/AsyncSSLSocket.h:32,
                 from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/ssl/SSLUtil.h:14,
                 from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/acceptor/ServerSocketConfig.h:15,
                 from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/acceptor/Acceptor.h:12,
                 from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/acceptor/Acceptor.cpp:10:
/usr/include/folly/Memory.h:49:1: note: candidate: template<class T, class ... Args> typename std::enable_if<(! std::is_array< <template-parameter-1-1> >::value), std::unique_ptr<_Codecvt> >::type folly::make_unique(Args&& ...)
 make_unique(Args&&... args) {
 ^
/usr/include/folly/Memory.h:49:1: note:   template argument deduction/substitution failed:
In file included from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/acceptor/Acceptor.h:14:0,
                 from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/acceptor/Acceptor.cpp:10:
/home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/acceptor/ConnectionManager.h:63:58: note:   cannot convert 'std::forward<folly::EventBase*&>((* & args#0))' (type 'folly::EventBase*') to type 'folly::DelayedDestruction::Destructor&&'
  return folly::make_unique<ConnectionManager, Destructor>(
                                                          ^
In file included from /usr/include/folly/io/Cursor.h:31:0,
                 from /usr/include/folly/io/async/AsyncSSLSocket.h:32,
                 from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/ssl/SSLUtil.h:14,
                 from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/acceptor/ServerSocketConfig.h:15,
                 from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/acceptor/Acceptor.h:12,
                 from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/acceptor/Acceptor.cpp:10:
/usr/include/folly/Memory.h:56:1: note: candidate: template<class T> typename std::enable_if<std::is_array< <template-parameter-1-1> >::value, std::unique_ptr<_Codecvt> >::type folly::make_unique(size_t)
 make_unique(const size_t n) {
 ^
/usr/include/folly/Memory.h:56:1: note:   template argument deduction/substitution failed:
In file included from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/acceptor/Acceptor.h:14:0,
                 from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/acceptor/Acceptor.cpp:10:
/home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/acceptor/ConnectionManager.h:63:58: error: wrong number of template arguments (2, should be 1)
  return folly::make_unique<ConnectionManager, Destructor>(
                                                          ^
In file included from /usr/include/folly/io/Cursor.h:31:0,
                 from /usr/include/folly/io/async/AsyncSSLSocket.h:32,
                 from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/ssl/SSLUtil.h:14,
                 from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/acceptor/ServerSocketConfig.h:15,
                 from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/acceptor/Acceptor.h:12,
                 from /home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/acceptor/Acceptor.cpp:10:
/usr/include/folly/Memory.h:64:1: note: candidate: template<class T, class ... Args> typename std::enable_if<(std::extent<_Tp>::value != 0), std::unique_ptr<_Codecvt> >::type folly::make_unique(Args&& ...) <deleted>
 make_unique(Args&&...) = delete;
 ^
/usr/include/folly/Memory.h:64:1: note:   template argument deduction/substitution failed:
/usr/include/folly/Memory.h: In substitution of 'template<class T, class ... Args> typename std::enable_if<(std::extent<_Tp>::value != 0), std::unique_ptr<_Codecvt> >::type folly::make_unique(Args&& ...) [with T = wangle::ConnectionManager; Args = {folly::DelayedDestruction::Destructor}]':
/home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/../wangle/acceptor/ConnectionManager.h:63:58:   required from 'static wangle::ConnectionManager::UniquePtr wangle::ConnectionManager::makeUnique(Args&& ...) [with Args = {folly::EventBase*&, const std::chrono::duration<long int, std::ratio<1l, 1000l> >&, wangle::Acceptor*}; wangle::ConnectionManager::UniquePtr = std::unique_ptr<wangle::ConnectionManager, folly::DelayedDestruction::Destructor>]'
/home/renan/aur/wangle/src-cp/wangle-0.13.0/wangle/acceptor/Acceptor.cpp:87:54:   required from here
/usr/include/folly/Memory.h:64:1: error: no type named 'type' in 'struct std::enable_if<false, std::unique_ptr<wangle::ConnectionManager, std::default_delete<wangle::ConnectionManager> > >'
CMakeFiles/wangle.dir/build.make:62: recipe for target 'CMakeFiles/wangle.dir/acceptor/Acceptor.cpp.o' failed
make[2]: *** [CMakeFiles/wangle.dir/acceptor/Acceptor.cpp.o] Error 1
make[1]: *** [CMakeFiles/wangle.dir/all] Error 2
CMakeFiles/Makefile2:522: recipe for target 'CMakeFiles/wangle.dir/all' failed
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
00:38:05: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project Project (kit: Desktop)
When executing step "Make"
00:38:05: Elapsed time: 00:03.
```

**Comment by djwatson** [comment]
should be fixed in recent versions

**Comment by mmlac** [comment]
FYI, it's still an issue when compiling with examples on arch:

```
Scanning dependencies of target BroadcastProxy
[ 33%] Building CXX object CMakeFiles/BroadcastProxy.dir/example/broadcast/BroadcastProxy.cpp.o
[ 34%] Linking CXX executable bin/BroadcastProxy
/usr/bin/ld: CMakeFiles/BroadcastProxy.dir/example/broadcast/BroadcastProxy.cpp.o: undefined reference to symbol 'pthread_setname_np@@GLIBC_2.12'
/usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/BroadcastProxy.dir/build.make:107: bin/BroadcastProxy] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/BroadcastProxy.dir/all] Error 2
make: *** [Makefile:139: all] Error 2
```

Builds fine without expamles though, but still, thought it's worth mentioning.
